# Generated by Django 3.2.9 on 2021-12-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snacks',
            name='description',
            field=models.TextField(default='it is very good'),
        ),
    ]
